#! /usr/bin/env ruby

print 'Auto snapping'
 loop do
   msg = File.read('.git/ATOM_COMMIT_EDITMSG')
   if msg == ""
     `script/snapshot "autosnapped"`
   else
     `script/snapshot "autosnapped\n\n#{msg}"`
   print '.'
   sleep 20
 end
