#! /usr/bin/env ruby

print 'Auto snapping'
 loop do
   if File.exists? '.git/ATOM_COMMIT_EDITMSG'
     msg = File.read('.git/ATOM_COMMIT_EDITMSG')
     if msg == ""
       `script/snapshot "autosnapped"`
     else
       `script/snapshot "autosnapped\n\n#{msg}"`
     end
   else
    `script/snapshot "autosnapped"`
   end
   print '.'
   sleep 20
 end
